name: Deploy Vite Application

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  

      - name: Build Docker Image
        run: docker build -t shinkhal/resturant_frontend:latest .

      - name: Publish Image to Docker Hub
        run: docker push shinkhal/resturant_frontend:latest
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull shinkhal/resturant_frontend:latest 

      - name: Delete Old Container
        run: docker rm -f resturant_frontend-container || true

      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name resturant_frontend-container shinkhal/resturant_frontend:latest
